### ISSUE TITLE
compare_results.sh gets the wrong column?

### ISSUE THREAD

**Issue by buchanae** [mikisvaz/PCAWG-Docker-Test#1]
I'm learning how to compare VCFs from your code (thanks!) and I'm studying this line:
https://github.com/mikisvaz/PCAWG-Docker-Test/blob/master/bin/compare_result.sh#L55

Specifically the `cut` command. That's pulling column number 4, which is the reference base. Wouldn't the reference base always be the same for all runs of a variant caller that using the same reference?

Probably I'm just misunderstanding the code, but wanted to double check. Thanks!

**Comment by mikisvaz** [comment]
Oh dear, let me check that again. Thanks so much for the heads up

**Comment by mikisvaz** [comment]
@buchanae you where absolutely right. Good thing you noticed! I've corrected it in the latest commit
